### ISSUE TITLE
500 init is not a function

### ISSUE THREAD

**Issue by FKonig** [nuxt-modules/strapi#278]
### Version
@nuxtjs/strapi: v1.5.0
nuxt: v3.0.0-rc.4
node: v16.16.0
strapi: v4.3.6
Linux Pop_OS 20.04

### Reproduction Link

https://github.com/FKonig/NuxtStrapi_Bug

### Steps to reproduce
Normal minimal installation like in the linked repo.
Opening http://localhost:3000 -> `500 init is not a function`

### What is Expected?
Successful start of the application

### What is actually happening?
Browser:
![image](https://user-images.githubusercontent.com/26013208/188049793-9ee0173c-da7a-4650-a5de-d74b7f4700c1.png)

Terminal:
```
[nuxt] [request error] init is not a function
  at Module.useState (./.nuxt/dist/server/server.mjs:993:26)  
  at Module.useStrapiUser (./.nuxt/dist/server/server.mjs:3184:51)  
  at Module.useStrapiAuth (./.nuxt/dist/server/server.mjs:3053:38)  
  at ./.nuxt/dist/server/server.mjs:3020:47  
  at fn (./.nuxt/dist/server/server.mjs:434:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:42:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:436:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:391:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:401:11)  
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)
[nuxt] [request error] init is not a function
  at Module.useState (./.nuxt/dist/server/server.mjs:993:26)  
  at Module.useStrapiUser (./.nuxt/dist/server/server.mjs:3184:51)  
  at Module.useStrapiAuth (./.nuxt/dist/server/server.mjs:3053:38)  
  at ./.nuxt/dist/server/server.mjs:3020:47  
  at fn (./.nuxt/dist/server/server.mjs:434:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:42:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:436:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:391:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:401:11)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Mechse** [comment]
Hello FKonig,
I just cloned your reproduction repository.
Unfortunately it works fine on my machine.

If you use an functions from the @nuxtjs/strapi repo please consider this issue: #282 and there is an open pull request for this bug: #281
