### ISSUE TITLE
[useAsyncData] Data in named variable

### ISSUE THREAD

**Issue by luixal** [nuxt-modules/strapi#291]
Hi,

When using `useAsyncData` I can get the right content if I use this code:

```js
<script setup>
const { find } = useStrapi4();

const { data, pending, refresh, error } = await useAsyncData(
  'events',
  () => find('events')
);
</script>
```

but... as `data` is too generic and I need to get content from two different entities, I just tried to make the change proposed in [nuxt's useAsyncData example](https://v3.nuxtjs.org/migration/component-options/#using-composables):

```js
<script setup>
  // Define params wherever, through `defineProps()`, `useRoute()`, etc.
  const { data: post, refresh } = await useAsyncData('post', () => $fetch(`https://api.nuxtjs.dev/posts/${params.id}`) )
  // Or instead - useFetch is a convenience wrapper around useAsyncData when you're just performing a simple fetch
  const { data: post, refresh } = await useFetch(`https://api.nuxtjs.dev/posts/${params.id}`)
</script>
```

so, I changed my code to this (notice the `data: events` change):

```js
<script setup>
const { find } = useStrapi4();

const { data: events, pending, refresh, error } = await useAsyncData(
  'events',
  () => find('events')
);
</script>
```

but this results in an error like this (on server console):

```
RefImpl {
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: {
    error: {
      status: 500,
      name: 'UnknownError',
      message: 'fetch failed ()',
      details: FetchError: fetch failed ()
          at async /home/user/.../node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:44:14
          at async setup (/home/user/.../app.vue:50:12)
    }
  },
  _value: {
    error: {
      status: 500,
      name: 'UnknownError',
      message: 'fetch failed ()',
      details: FetchError: fetch failed ()
          at async /home/user/.../node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:44:14
          at async setup (/home/user/.../app.vue:50:12)
    }
  }
```

If I replace the `find('events')` with the `$fetch('https://api.nuxtjs.dev/posts/1')` from the example, it works perfectly populating the `events` variable.

Any idea about this?

Thanks!

**Comment by luixal** [comment]
In fact, It doesn't work like that, I have to add the `{server: false}` option for it to work. Like this: 

```js
const { data, pending, refresh, error } = await useAsyncData(
  'events',
  () => find('events'),
  {server: false}
);
```

A whole example or blog post about whole creation with an example API would be great to have...

**Comment by luixal** [comment]
I'm closing this as I was doing a fast test of this module and haven't set it up properly.

Once I set up the auth middleware, it worked properly. Didn't know why I got data in `data` variable and no in the `events` one but... now it working.
