### ISSUE TITLE
Nuxt crashes upon initialization if token cookie exists in browser

### ISSUE THREAD

**Issue by sriparashiva** [nuxt-modules/strapi#329]
### Version
@nuxtjs/strapi: v1.7.1
nuxt: v3.1.1

### Steps to reproduce
Used the authenticateProvider() function and it worked successfully, setting a cookie in the browser named 'strapi_jwt'.

`await authenticateProvider( 'google', route.query.access_token )`

After this, if I close the Nuxt tab and re-open it (which causes Nuxt to initialize), it crashes with an error 500.

If I use the browser inspector and manually delete the 'strapi_jwt' cookie, everything works fine again and Nuxt is able to initialize. 

I think it might be related to the fetchUser() function which is called by default upon initialization of Nuxt by the plugin (mentioned in the docs [here](https://strapi.nuxtjs.org/auth#fetchuser)). The plugin seems to find the token value set in the cookie and tries to fetch the user and crashes for some reason. If there is no token found, no error occurs.

### What is Expected?
Nuxt should initialize normally

### What is actually happening?
Nuxt initialization crashing showing the following error:

`
500

Error

at createError (./node_modules/nuxt/dist/app/composables/error.mjs:35:38)
at showError (./node_modules/nuxt/dist/app/composables/error.mjs:10:15)
at fn (./node_modules/nuxt/dist/app/nuxt.mjs:151:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)
at Module.callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:153:23)
at ./node_modules/nuxt/dist/app/components/nuxt-root.js:36:37
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
at callWithAsyncErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
at Array.hook.__weh.hook.__weh (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2702:29)
`

**Comment by sriparashiva** [comment]
Apologies. My Strapi instance had one of the content types inaccessible to authenticated users which was causing the issue.
