### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot find module './stringify'

### ISSUE THREAD

**Issue by Zignature** [nuxt-modules/strapi#376]
### Version
@nuxtjs/strapi: 1.10.1
nuxt: 3.8.2
node: 20.9.0 (Volta)
npm: 10.2.3
@strapi/strapi: 4.15.5

### Reproduction Link

I have no idea how to reproduce. The error was there all of a sudden
### What is Expected?
I expect a nice website in my browser

### What is actually happening?
I get a 500 error

```
[nuxt] [request error] [unhandled] [500] Cannot find module './stringify'
Require stack:
- C:\webdev\- Vue Playground\- Nuxt\primevue\nuxt-primevue-strapi\qs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
  at Module._load (node:internal/modules/cjs/loader:985:27)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
  at require (node:internal/modules/helpers:176:18)
  at C:\webdev\- Vue Playground\- Nuxt\primevue\nuxt-primevue-strapi\qs:3:17
  at ViteNodeRunner.directRequest (/C:/webdev/-%20Vue%20Playground/-%20Nuxt/primevue/nuxt-primevue-strapi/node_modules/vite-node/dist/client.mjs:341:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/C:/webdev/-%20Vue%20Playground/-%20Nuxt/primevue/nuxt-primevue-strapi/node_modules/vite-node/dist/client.mjs:197:14)
  at async ViteNodeRunner.dependencyRequest (/C:/webdev/-%20Vue%20Playground/-%20Nuxt/primevue/nuxt-primevue-strapi/node_modules/vite-node/dist/client.mjs:231:12)
  at async C:\webdev\- Vue Playground\- Nuxt\primevue\nuxt-primevue-strapi\node_modules\@nuxtjs\strapi\dist\runtime\composables\useStrapiClient.mjs:2:31
```

**Comment by Zignature** [comment]
`@nuxt/strapi` doesn't agree with `nuxt-primevue` or vice versa.

I can run both packages fine separately, but if I run both packages the error occurs.

I figured maybe on installation one package overwrites something the other package relies on, so I tried different orders of installation. To no avail.

Still, it's very weird 'cause I had them running side by side perfectly. Than I closed the laptop to open it again 2 hours later and since then the error occurs.

### Versions:
- nuxt: "^3.8.2
- @nuxtjs/strapi: "^1.10.1"
- nuxt-primevue: "^0.2.2"

**Comment by Zignature** [comment]
Same happens with `@invictus.codes/nuxt-vuetify`

**Comment by Zignature** [comment]
No problems with `@nuxt/ui`

**Comment by x8BitRain** [comment]
This also happens when you have `ssr: true` when you use packages that don't play nicely with SSR or aren't explicitly designed for Nuxt SSR. 

Setting `ssr: false` in your Nuxt config usually fixes this issue, at this point you should probably ask yourself if you really want to use SSR or not.

**Comment by MathiasOdlund** [comment]
Having the same issue

**Comment by benjamincanac** [comment]
`qs` has been removed entirely in https://github.com/nuxt-modules/strapi/commit/d755086043fb572e27231b257259bbdf18c42725, this should no longer happen on next release!
